services:
  backend:
    image: michael0221/eshop-backend:ec2
    container_name: mern-backend
    restart: unless-stopped
    env_file:
      - ~/deploy/.env
    environment:
      NODE_ENV: production
      PORT: 5000
    ports:
      - "8000:5000"
    networks:
      - mern-network

  frontend:
    image: michael0221/eshop-mern-frontend:ec2
    container_name: mern-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DOZZLE_BASE: /logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mern-network

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - mern-network

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/deploy/frontend/promtail-config.yml:/etc/promtail/config.yml
    networks:
      - mern-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SERVER_ROOT_URL: http://18.142.177.28/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - ~/deploy/grafana/data:/var/lib/grafana
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
